# Generated by Django 4.2.11 on 2024-03-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prods_servs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service',
            new_name='service_name',
        ),
    ]
