# Generated by Django 4.2.11 on 2024-03-12 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_rename_category_service_business_service'),
        ('prods_servs', '0002_rename_service_service_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to='businesses.service_business'),
        ),
    ]
