# Generated by Django 4.2.11 on 2024-03-12 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_rename_service_service_business_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_business',
            old_name='category',
            new_name='service',
        ),
    ]
