# Generated by Django 4.2.11 on 2024-03-12 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_rename_category_service_business_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_business',
            name='service',
        ),
    ]
