# Generated by Django 4.2.11 on 2024-03-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_service_business_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_business',
            old_name='service',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='business',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='business',
            name='open_time',
        ),
    ]
